version: '3.9'
services:
  media-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/mediaApp
      JWT_SECRET: your_jwt_secret
  mongo:
    image: mongo
    ports:
      - "27017:27017"
